export const ACTION_TYPES = {
  AUTH_LOGIN_PENDING: 'AUTH_LOGIN_PENDING',
  AUTH_LOGIN_FULFILLED: 'AUTH_LOGIN_FULFILLED',
  AUTH_LOGIN_REJECTED: 'AUTH_LOGIN_REJECTED',

  AUTH_LOGOUT_PENDING: 'AUTH_LOGOUT_PENDING',
  AUTH_LOGOUT_FULFILLED: 'AUTH_LOGOUT_FULFILLED',
  AUTH_LOGOUT_REJECTED: 'AUTH_LOGOUT_REJECTED',

  AUTH_HIDE_ERROR: 'AUTH_HIDE_ERROR',

  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER',

  TOAST_MESSAGE: 'TOAST_MESSAGE',
};
